# Generated by Django 5.2.12 on 2026-04-01 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useravatar_userpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^8\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='tg_name',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='diploma_year',
            field=models.PositiveSmallIntegerField(default=2028),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='start_year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
    ]
