# Generated by Django 5.2.12 on 2026-04-01 15:06

from django.db import migrations

def update_students_without_group(apps, schema_editor):
    Student = apps.get_model('users', 'Student')
    Student.objects.filter(user_group__isnull=True).update(is_student=False)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_date_of_birth_student_is_student_and_more'),
    ]

    operations = [
        migrations.RunPython(update_students_without_group),
    ]
