# Generated by Django 5.2.12 on 2026-04-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20260401_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='group_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
